spring:
  h2.console:
    enabled: true
    path: /h2-console
  jpa:
    #    database-platform : org.hibernate.dialect.MySQL5Dialect
    #    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database-platform: org.hibernate.dialect.H2Dialect
    database: h2
    generate-ddl: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    defer-datasource-initialization: true
    properties:
      hibernate.default_batch_fetch_size: 1000


  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  redis:
    host: localhost
    port: 6379

  main:
    web-application-type: reactive


  #
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
#    allow-bean-definition-overriding: true

logging:
  level:
    org.springframework.web.reactive.function.server: trace

